clientVersion: 0.1.2
env: DEV
imagePullSecrets: []
client:
  name: tripstagger-client
  pullPolicy: IfNotPresent
  replicas: 2
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 1000m
      memory: 2G
tier:
  frontend: frontend
