clientVersion: 0.1.6
env: TEST
namespace: tripstagger
imagePullSecrets: []
client:
  url: tripstagger.com
  name: tripstagger-client
  pullPolicy: IfNotPresent
  replicas: 2
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 1000m
      memory: 2G
ingress:
  tls:
  - secretName: chart-example-tls
    hosts:
    - tripstagger.com
tier:
  frontend: frontend
