# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        app:
          description: 'App name to update'
          required: true        
          type: choice
          options:
          - clientVersion
        version:
          description: 'New version'
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  release-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Update component version
        run: |
            pip install pyyaml
            python update-element-version.py $app $version
        env:
          app: ${{ github.event.inputs.app }}
          version: ${{ github.event.inputs.version }}
      - name: Commit component version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat(upgrade): App ${{ github.event.inputs.app}} Version ${{ github.event.inputs.version }}"
          file_pattern: tripstagger/values.yaml
          skip_fetch: true    
          skip_checkout: true

