# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        app:
          description: 'App name to update'
          required: true        
          type: choice
          options:
          - clientVersion
        version:
          description: 'New version'
          required: true
        type:
          description: 'Type of the release'
          required: true        
          default: patch
          type: choice
          options:
          - patch
          - minor
          - major

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  release-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PrepareNode
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Update component version
        run: |
            pip install pyyaml
            python update-element-version.py $app $version
        env:
          app: ${{ github.event.inputs.app }}
          version: ${{ github.event.inputs.version }}
      - name: Commit component version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat(upgrade): Update ${{ github.event.inputs.app}} to version ${{ github.event.inputs.version }}"
          file_pattern: tripstagger/values.yaml
          skip_fetch: true    
          skip_checkout: true
      - uses: egordm/gha-yarn-node-cache@v1
      - name: Install js packages
        run: yarn install
      - name: Release new version
        run: yarn release@$type
        env:
          type: ${{ github.event.inputs.type }}

